<a href="https://colab.research.google.com/github/lelyamalia/Kelas-Dasar-PSDS-PD4/blob/main/PSDS_12_12_2022.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas DataFrame

In [ ]:
import pandas as pd

# Membuat DataFrame
Membuat matriks menggunakan list

In [ ]:
# List
list_buah = ['jeruk', 'Pepaya', 'Mangga', 'Rambutan', 'Leci', 'Nanas', 'Manggis']

# Membuat DataFrame menggunakan list_buah
df = pd.DataFrame(list_buah)
df

0
0     jeruk
1    Pepaya
2    Mangga
3  Rambutan
4      Leci
5     Nanas
6   Manggis

Membuat Data Frame Menggunakan List dan Fungsi Zip

In [ ]:
# List Buah(string)
list_buah = ['jeruk', 'Pepaya', 'Mangga', 'Rambutan', 'Leci', 'Nanas', 'Manggis']

# List Berat Buah (Integer)
list_berat = [50, 800, 150, 10, 2, 300, 70]

# Membuat DataFrame Menggunakan Dua Buah List dengan Fungsi Zip
df = pd.DataFrame(list(zip(list_buah, list_berat)),
                  columns = ['Nama Buah', 'Berat Buah'])
df

Nama Buah  Berat Buah
0     jeruk          50
1    Pepaya         800
2    Mangga         150
3  Rambutan          10
4      Leci           2
5     Nanas         300
6   Manggis          70

Membuat DataFrame Menggunakan List Multidimensi

In [ ]:
# List Multidimensi (Nama, Usia)
lst = [['Bejo', 25], ['Ari', 30],
        ['Asep', 26], ['Richard', 32]]

df = pd.DataFrame(lst, columns =['Nama', 'Usia'])
df

Nama  Usia
0     Bejo    25
1      Ari    30
2     Asep    26
3  Richard    32

Membuat DataFrame Menggunakan Dictionary

In [ ]:
mobil = {'Type Mobil': ['Honda Civic', 'Toyota Corolla', 'Ford Focus', 'Audi A4'],
         'Harga(USD)': [22000, 25000, 27000, 35000]
         }

df = pd.DataFrame(mobil)

df

Type Mobil  Harga(USD)
0     Honda Civic       22000
1  Toyota Corolla       25000
2      Ford Focus       27000
3         Audi A4       35000

# Mengimport DataFrame

# Import DataFrame dari file CSV

In [ ]:
df_super_store = pd.read_csv('Super-Store-Dataset.csv')
df_super_store.head()

order_id  order_date customer_id    segment         category  \
0  CA-2016-152156   11/8/2016    CG-12520   Consumer        Furniture   
1  CA-2016-152156   11/8/2016    CG-12520   Consumer        Furniture   
2  CA-2016-138688   6/12/2016    DV-13045  Corporate  Office Supplies   
3  US-2015-108966  10/11/2015    SO-20335   Consumer        Furniture   
4  US-2015-108966  10/11/2015    SO-20335   Consumer  Office Supplies   

  sub_category     sales  quantity    profit  
0    Bookcases  261.9600         2   41.9136  
1       Chairs  731.9400         3  219.5820  
2       Labels   14.6200         2    6.8714  
3       Tables  957.5775         5 -383.0310  
4      Storage   22.3680         2    2.5164

# Import DataFrame dari File Excel

In [ ]:
df_pilkada = pd.read_excel('/content/datasetpilkadadki.xlsx')
df_pilkada.head()

Id Sentiment Pasangan Calon  \
0   1  negative     Agus-Sylvi   
1   2  negative     Agus-Sylvi   
2   3  negative     Agus-Sylvi   
3   4  negative     Agus-Sylvi   
4   5  negative     Agus-Sylvi   

                                          Text Tweet  
0  Banyak akun kloning seolah2 pendukung #agussil...  
1  #agussilvy bicara apa kasihan yaa...lap itu ai...  
2  Kalau aku sih gak nunggu hasil akhir QC tp lag...  
3  Kasian oh kasian dengan peluru 1milyar untuk t...  
4  Maaf ya pendukung #AgusSilvy..hayo dukung #Ani...

# Numpy Array

In [ ]:
import numpy as np

# Membuat Array NumPy

In [ ]:
list_1 = [1,2,3,4,5]
arr_1 = np.array([list_1])
arr_1

array([[1, 2, 3, 4, 5]])

In [ ]:
print(np.zeros((2,5)))  # membuat array dengan nilai 0 dengan shape (5,5)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
print(np.ones((5,3)))  # membuat array dengan nilai 1 dengan shape (5,5)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
print(np.arange(1, 10, 2)) #arange(start, stop, step)

[1 3 5 7 9]


In [ ]:
print(np.linspace(1, 10, 2)) #linespace(start, stop, step)

[ 1. 10.]


In [ ]:
print(np.logspace(1, 10, 2)) #logspace

[1.e+01 1.e+10]


In [ ]:
print(np.full((2,2), 4)) #Membuat array matriks dengan shape (2,2) dengan elemen 99

[[4 4]
 [4 4]]


In [ ]:
A = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(A)

print(np.full_like(A, 3)) #Membuat array matriks dengan shape yang sama dengan A dengan semua elemen 3

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
[[3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3]]


In [ ]:
print(np.random.rand(4,2)) #Random decimal numbers

[[0.32072593 0.0100265 ]
 [0.09557404 0.37320434]
 [0.12382426 0.97411801]
 [0.42227452 0.73279554]]


In [ ]:
print(np.random.randint(-4, 8, size=(3,3))) #Random integer values

[[ 3  4  7]
 [ 6  2  2]
 [-2  6  0]]


In [ ]:
print(np.identity(5)) #Membuat matriks identitas

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
arr = np.array([[1,2,3]]) #Membuat matriks dengan perulangan array
r1 = np.repeat(arr, 3, axis = 0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


#Metode metode pada Array

array.ndim
Metode ini digunakan untuk mengetahui dimensi dari array

In [ ]:
a = np.array([29, 28, 30], dtype='int32')
print(a)

print("Dimensi dari array a adalah ", a.ndim)

[29 28 30]
Dimensi dari array a adalah  1


array.shape
Metode ini digunakan untuk mengetahui ukuran (variabel dan baris) dari array

In [ ]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

print("Ukuran Sha")